# Generated by Django 4.0.1 on 2022-01-30 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_record_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='name',
        ),
        migrations.DeleteModel(
            name='Config',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
