# Generated by Django 4.0.1 on 2022-02-02 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_record_name_delete_config_delete_record'),
        ('config', '0003_alter_config_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.user', to_field='name'),
        ),
    ]
