# Generated by Django 4.0.1 on 2022-02-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_alter_config_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
